channels:
- defaults
- conda-forge
dependencies:
- python=3.9.7
- pip
- pip:
  - mlflow==1.30.0
  - cloudpickle==2.0.0
  - click==8.0.4
  - Flask==2.0.3
  - pandas==1.4.1
  - scikit-learn==1.0.2
  - configparser==5.0.2
  - boto3==1.21.8
  - transformer==4.20.0
name: ecomm-recom-env
